[project]
name = "clipboard_demo"
version = "0.0.2"
requires-python = ">= 3.11"
dependencies = [
    "textual",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
clipboard-demo = "clipboard_demo.text_clipboard:main"