[project]
name = "cpdemo"
version = "0.0.4"
requires-python = ">= 3.11"
dependencies = [
    "textual",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
clipboard-demo = "cpdemo.text_clipboard:main"